### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by MaXinjian** [waynesun09/reportportal-operator#4]
Just wonder our project  is  Apache Licensed，howerver we  install ansible collections(community.kubernetes) which is GPLv3 Licensed. As we know, GPLv3 is infectious; any code that uses a GPL library automatically becomes GPL as well.
Doesn't it introduce problem?

**Comment by waynesun09** [comment]
Thanks for you quesiton.

According to
https://www.apache.org/licenses/GPL-compatibility.html

`This licensing incompatibility applies **_only_** when some Apache project software becomes a derivative work of some GPLv3 software, because then the Apache software would have to be distributed under GPLv3. This would be incompatible with ASF's requirement that all Apache software must be distributed under the Apache License 2.0.`

this project is not derivative work of Ansible and Ansible collections, so it should not be a problem.
I have limited understanding with this complex issue, I'll update on this if get more feedback from others.

**Comment by waynesun09** [comment]
@MaXinjian follow-up on the question, I have consulted other people with more legal knowledge and the feedback is as Ansible components are simply used as they are expected to be used without any relationship between the GPLv3-licensed files and other files that would require the other files to be licensed under GPLv3.

I'll close this now, feel free to add more comments.

Thanks
